(window.JST || (window.JST = {}))['example'] = 
(function(data) {
  return (function() {
    var __runtime;
    __runtime = Runtime(this);
    __runtime.push(document.createDocumentFragment());
    __runtime.push(document.createElement("div"));
    __runtime.classes("example", this.hideInactive);
    __runtime.push(document.createElement("h4"));
    __runtime.classes("title");
    __runtime.text(this.header);
    __runtime.pop();
    __runtime.push(document.createElement("hr"));
    __runtime.classes("divider");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("description");
    __runtime.push(document.createElement("p"));
    __runtime.text(this.description);
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("left-column");
    __runtime.push(document.createElement("textarea"));
    __runtime.classes("code");
    __runtime.attribute("placeholder", "template code");
    __runtime.attribute("value", this.sourceTemplate);
    __runtime.pop();
    __runtime.push(document.createElement("textarea"));
    __runtime.classes("code");
    __runtime.attribute("placeholder", "JavaScript code");
    __runtime.attribute("value", this.sourceCode);
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("right-column");
    __runtime.push(document.createElement("button"));
    __runtime.classes("reset");
    __runtime.attribute("click", this.reset);
    __runtime.text("Reset this example\n");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("output");
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("competing-example");
    __runtime.push(document.createElement("h3"));
    __runtime.text("Backbone\n");
    __runtime.pop();
    __runtime.push(document.createElement("a"));
    __runtime.attribute("href", "http://jsfiddle.net/icoxfog417/pfxP5/");
    __runtime.attribute("target", "_blank");
    __runtime.text("Compare to jsFiddle\n");
    __runtime.pop();
    __runtime.pop();
    __runtime.pop();
    return __runtime.pop();
  }).call(data);
});
