(window.JST || (window.JST = {}))['todo'] = 
(function(data) {
  return (function() {
    var __runtime;
    __runtime = Runtime(this);
    __runtime.push(document.createDocumentFragment());
    __runtime.push(document.createElement("div"));
    __runtime.classes("todo-example");
    __runtime.push(document.createElement("h4"));
    __runtime.classes("title");
    __runtime.text("It's just JavaScript\n");
    __runtime.pop();
    __runtime.push(document.createElement("hr"));
    __runtime.classes("divider");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("description");
    __runtime.push(document.createElement("p"));
    __runtime.text("JavaScript with zero dependencies. Write template backing objects with clean public APIs using the style of JavaScript you love the most. Don't mess with a model system or learn the differences between a Backbone Collection and a native Array.\n");
    __runtime.pop();
    __runtime.push(document.createElement("p"));
    __runtime.text("Take a look at how easy it is to create a TODO list.\n");
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("left-column");
    __runtime.push(document.createElement("textarea"));
    __runtime.classes("code");
    __runtime.attribute("placeholder", "TODO example template");
    __runtime.attribute("value", this.sourceTemplate);
    __runtime.pop();
    __runtime.push(document.createElement("textarea"));
    __runtime.classes("code");
    __runtime.attribute("placeholder", "TODO example JavaScript");
    __runtime.attribute("value", this.sourceCode);
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("right-column");
    __runtime.push(document.createElement("button"));
    __runtime.classes("reset");
    __runtime.attribute("click", this.reset);
    __runtime.text("Reset this example\n");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.id("todo-output");
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.id("backbone-todo");
    __runtime.push(document.createElement("h3"));
    __runtime.text("Backbone\n");
    __runtime.pop();
    __runtime.push(document.createElement("a"));
    __runtime.attribute("href", "http://jsfiddle.net/icoxfog417/pfxP5/");
    __runtime.attribute("target", "_blank");
    __runtime.text("Compare to jsFiddle\n");
    __runtime.pop();
    __runtime.pop();
    __runtime.pop();
    return __runtime.pop();
  }).call(data);
});
